"""Fix document_chunks page_numbers column type

Revision ID: 22b93abc9c1e
Revises: add_hybrid_search_schema
Create Date: 2025-11-02 17:37:56.184992

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '22b93abc9c1e'
down_revision: Union[str, Sequence[str], None] = 'add_hybrid_search_schema'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_search_config_id'), table_name='search_config')
    op.drop_table('search_config')
    op.alter_column('document_chunks', 'page_numbers',
               existing_type=postgresql.ARRAY(sa.INTEGER()),
               type_=sa.Text(),
               existing_nullable=True)
    op.drop_index(op.f('idx_chunks_search_vector'), table_name='document_chunks', postgresql_using='gin')
    op.drop_index(op.f('idx_chunks_text_gin'), table_name='document_chunks', postgresql_using='gin')
    op.drop_index(op.f('idx_chunks_text_hash'), table_name='document_chunks')
    # Skip problematic index creation - text is too large for indexing
    op.drop_column('document_chunks', 'search_vector')
    op.alter_column('embeddings', 'page_numbers',
               existing_type=postgresql.ARRAY(sa.INTEGER()),
               type_=sa.Text(),
               existing_nullable=True)
    op.alter_column('search_history', 'search_results',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.Text(),
               existing_nullable=True)
    op.alter_column('search_history', 'search_metadata',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.Text(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('search_history', 'search_metadata',
               existing_type=sa.Text(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('search_history', 'search_results',
               existing_type=sa.Text(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('embeddings', 'page_numbers',
               existing_type=sa.Text(),
               type_=postgresql.ARRAY(sa.INTEGER()),
               existing_nullable=True)
    op.add_column('document_chunks', sa.Column('search_vector', postgresql.TSVECTOR(), autoincrement=False, nullable=True))
    op.drop_index('idx_chunks_text', table_name='document_chunks', postgresql_using='gin')
    op.create_index(op.f('idx_chunks_text_hash'), 'document_chunks', [sa.literal_column('md5(chunk_text)')], unique=False)
    op.create_index(op.f('idx_chunks_text_gin'), 'document_chunks', [sa.literal_column("to_tsvector('french'::regconfig, chunk_text)")], unique=False, postgresql_using='gin')
    op.create_index(op.f('idx_chunks_search_vector'), 'document_chunks', ['search_vector'], unique=False, postgresql_using='gin')
    op.alter_column('document_chunks', 'page_numbers',
               existing_type=sa.Text(),
               type_=postgresql.ARRAY(sa.INTEGER()),
               existing_nullable=True)
    op.create_table('search_config',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('config_key', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('config_value', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('search_config_pkey')),
    sa.UniqueConstraint('config_key', name=op.f('search_config_config_key_key'))
    )
    op.create_index(op.f('ix_search_config_id'), 'search_config', ['id'], unique=False)
    # ### end Alembic commands ###
